### PR TITLE
Remove laminas/laminas-i18n in favor of laminas/laminas-translator

### LINKED ISSUE #55: Laminas\I18n\Translator is a soft dependency
### Bug Report

When doing an class_implements for Laminas\Router\Http\TranslatorAwareTreeRouteStack

Error: Interface "Laminas\I18n\Translator\TranslatorAwareInterface" not found

|    Q        |   A
|------------ | ------
| Version(s)  | 3.12.0

#### How to reproduce

require this package
try class_implements for Laminas\Router\Http\TranslatorAwareTreeRouteStack (interface doesnt matter)
error occues

#### Expected behavior

Interface should exists by adding a depencency to this package

### PR DESCRIPTION
**Pull request by fezfez**
- Remove `laminas/laminas-i18n` from `composer.json`.
- Add `laminas/laminas-translator` to dependencies in `composer.json`.
- Adjust tests to mock `Laminas\Translator\TranslatorInterface` instead of relying on `laminas-i18n`.
- Update `psalm-baseline.xml` due to translator-related changes.
- Replace `Laminas\I18n\Translator\TranslatorInterface` with `Laminas\Translator\TranslatorInterface` in `Segment` and `TranslatorAwareTreeRouteStack`.
- remove usage of `TranslatorAwareInterface`

### CODE REVIEW

**Comment by fezfez** [comment]
need #101 before

**Comment by fezfez** [comment]
@gsteel could you merge 3.18.x into 4.0.x so i can rebase ?

**Comment by gsteel** [comment]
Lets get 3.18.0 released first, that will trigger a merge-up PR

**Comment by fezfez** [comment]
@gsteel ready for review

**Comment by fezfez** [comment]
also this should fix https://github.com/laminas/laminas-router/issues/55

File: test/Http/SegmentTest.php [hunk 1]
```diff
@@ -183,23 +182,36 @@ public static function routeProvider(): array
...
-        $domainLoader->expects($this->any())->method('load')->willReturn(new TextDomain(['fw' => 'fw-alternative']));
-
-        $translator->getPluginManager()->setService('test-en', $enLoader);
-        $translator->getPluginManager()->setService('test-de', $deLoader);
-        $translator->getPluginManager()->setService('test-domain', $domainLoader);
-        $translator->addTranslationFile('test-en', null, 'default', 'en-US');
-        $translator->addTranslationFile('test-de', null, 'default', 'de-DE');
-        $translator->addTranslationFile('test-domain', null, 'alternative', 'en-US');
+        $translator = $this->createMock(TranslatorInterface::class);
+        $translator->expects($this->any())
```
Comment (gsteel) [inline test/Http/SegmentTest.php]: Can you add an exact count here please?

Recent PHPUnit changes will fail with `$this->any()` due to moving to stricter mocking requirements.

```suggestion
        $translator->expects($this->exactly(999))
```

File: test/Http/TranslatorAwareTreeRouteStackTest.php [hunk 2]
```diff
@@ -5,31 +5,49 @@
...
 
     public function setUp(): void
     {
-        $this->testFilesDir = __DIR__ . '/_files';
-
-        $this->translator = new Translator();
-        $this->translator->addTranslationFile('phpArray', $this->testFilesDir . '/tokens.en.php', 'route', 'en');
-        $this->translator->addTranslationFile('phpArray', $this->testFilesDir . '/tokens.de.php', 'route', 'de');
+        $this->translator = $this->createMock(TranslatorInterface::class);
+        $this->translator->expects($this->any())
```
Comment (gsteel) [inline test/Http/TranslatorAwareTreeRouteStackTest.php]: Might be more difficult to replace this one - perhaps extract the mock to a private method such as `createTranslator(int $expectedCount)` or something…

File: test/Http/TranslatorAwareTreeRouteStackTest.php [hunk 3]
```diff
@@ -59,7 +76,7 @@ public function testTranslatorAwareInterfaceImplementation(): void
         $this->assertTrue($stack->isTranslatorEnabled());
 
         // Inject translator without text domain
-        $translator = new Translator();
+        $translator = $this->createMock(TranslatorInterface::class);
```
Comment (gsteel) [inline test/Http/TranslatorAwareTreeRouteStackTest.php]:
```suggestion
        $translator = $this->createStub(TranslatorInterface::class);
```

File: test/Http/TranslatorAwareTreeRouteStackTest.php [hunk 4]
```diff
@@ -86,7 +103,7 @@ public function testTranslatorAwareInterfaceImplementation(): void
 
     public function testTranslatorIsPassedThroughMatchMethod(): void
     {
-        $translator = new Translator();
+        $translator = $this->createMock(TranslatorInterface::class);
```
Comment (gsteel) [inline test/Http/TranslatorAwareTreeRouteStackTest.php]:
```suggestion
        $translator = $this->createStub(TranslatorInterface::class);
```

File: test/Http/TranslatorAwareTreeRouteStackTest.php [hunk 5]
```diff
@@ -106,7 +123,7 @@ public function testTranslatorIsPassedThroughMatchMethod(): void
 
     public function testTranslatorIsPassedThroughAssembleMethod(): void
     {
-        $translator = new Translator();
+        $translator = $this->createMock(TranslatorInterface::class);
```
Comment (gsteel) [inline test/Http/TranslatorAwareTreeRouteStackTest.php]:
```suggestion
        $translator = $this->createStub(TranslatorInterface::class);
```

**Review by gsteel — CHANGES_REQUESTED** [review]
Just a few minor test tweaks 👍

**Comment by fezfez** [comment]
@gsteel done, do you want me to rebase ?

**Review by gsteel — APPROVED** [review]
LGTM 👍 Thanks @fezfez
